
import React from 'react';
import { MatchPrediction } from '../types';
import { BarChart, Bar, XAxis, YAxis, ResponsiveContainer, Cell } from 'recharts';

interface Props {
  prediction: MatchPrediction;
  onAction?: (action: string) => void;
}

const PredictionDisplay: React.FC<Props> = ({ prediction, onAction }) => {
  const winData = [
    { name: 'Home', value: prediction.probabilities.homeWin, color: '#40a7e3' },
    { name: 'Draw', value: prediction.probabilities.draw, color: '#546e7a' },
    { name: 'Away', value: prediction.probabilities.awayWin, color: '#e53935' },
  ];

  const shareToX = () => {
    let text = `📊 AI Match Analysis: ${prediction.matchName}\n`;
    if (prediction.liveScore && prediction.liveScore.status !== 'scheduled') {
      text += `⚽ Live Score: ${prediction.liveScore.homeScore} - ${prediction.liveScore.awayScore}\n`;
    }
    text += `\n🎯 Verdict: ${prediction.suggestedBet}\n🔥 Confidence: ${prediction.confidence}%\n\nGenerated by BetPredict AI Bot\n#BetPredictAI #SportsAnalytics #BettingTips`;
    const url = window.location.href;
    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
    window.open(twitterUrl, '_blank');
  };

  const isLive = prediction.liveScore && (prediction.liveScore.status === 'live' || prediction.liveScore.status === 'HT');

  return (
    <div className="mt-3 space-y-4 text-left border-t border-white/5 pt-3">
      {/* Live Scoreboard */}
      {prediction.liveScore && (
        <div className="bg-gradient-to-r from-[#1a2b3c] to-[#0e1621] p-4 rounded-xl border border-[#40a7e3]/30 shadow-lg mb-2 overflow-hidden relative">
          {isLive && (
            <div className="absolute top-2 right-2 flex items-center gap-1.5 px-2 py-0.5 bg-red-500/10 rounded-full border border-red-500/20">
              <span className="w-1.5 h-1.5 bg-red-500 rounded-full animate-pulse"></span>
              <span className="text-[8px] font-black text-red-500 uppercase tracking-widest">Live</span>
            </div>
          )}
          <div className="flex items-center justify-between gap-4">
            <div className="flex-1 text-center">
              <p className="text-[10px] font-bold text-[#708499] uppercase mb-1 truncate">{prediction.matchName.split('vs')[0]}</p>
              <span className="text-3xl font-black text-white">{prediction.liveScore.homeScore}</span>
            </div>
            <div className="flex flex-col items-center">
              <div className="px-2 py-0.5 bg-white/5 rounded text-[10px] font-bold text-[#40a7e3] mb-1">
                {prediction.liveScore.time || prediction.liveScore.status}
              </div>
              <span className="text-[#708499] font-bold text-lg">:</span>
            </div>
            <div className="flex-1 text-center">
              <p className="text-[10px] font-bold text-[#708499] uppercase mb-1 truncate">{prediction.matchName.split('vs')[1]}</p>
              <span className="text-3xl font-black text-white">{prediction.liveScore.awayScore}</span>
            </div>
          </div>
        </div>
      )}

      {/* 1X2 Probabilities */}
      <div className="bg-[#0e1621] p-3 rounded-lg border border-white/5">
        <p className="text-[10px] font-bold text-[#708499] uppercase mb-2 flex justify-between">
          <span>Match Result (1X2)</span>
          <span className="text-emerald-400">Model Data</span>
        </p>
        <div className="h-32 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={winData} layout="vertical">
              <XAxis type="number" hide domain={[0, 100]} />
              <YAxis dataKey="name" type="category" stroke="#708499" fontSize={10} width={40} />
              <Bar dataKey="value" radius={[0, 4, 4, 0]} barSize={16}>
                {winData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={entry.color} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Correct Score & Asian Handicap Grid */}
      <div className="grid grid-cols-2 gap-2">
        <div className="bg-[#0e1621] p-3 rounded-lg border border-white/5">
          <p className="text-[9px] font-bold text-[#708499] uppercase mb-2">Likely Scores</p>
          <div className="space-y-1.5">
            {prediction.correctScores.map((s, i) => (
              <div key={i} className="flex justify-between items-center bg-white/5 px-2 py-1 rounded">
                <span className="text-xs font-bold text-white">{s.score}</span>
                <span className="text-[10px] text-emerald-400">{s.probability}%</span>
              </div>
            ))}
          </div>
        </div>
        <div className="bg-[#0e1621] p-3 rounded-lg border border-white/5">
          <p className="text-[9px] font-bold text-[#708499] uppercase mb-2">Asian Handicap</p>
          <div className="space-y-1.5">
            <div className="text-center py-1 bg-[#40a7e3]/10 rounded border border-[#40a7e3]/20 mb-1">
              <span className="text-[10px] font-bold text-[#40a7e3]">Line: {prediction.probabilities.asianHandicap.line}</span>
            </div>
            <div className="flex justify-between text-[10px]">
              <span className="text-[#708499]">Home:</span>
              <span className="text-white font-bold">{prediction.probabilities.asianHandicap.homeProb}%</span>
            </div>
            <div className="flex justify-between text-[10px]">
              <span className="text-[#708499]">Away:</span>
              <span className="text-white font-bold">{prediction.probabilities.asianHandicap.awayProb}%</span>
            </div>
          </div>
        </div>
      </div>

      {/* Specialty Markets: Corners & Cards */}
      <div className="bg-[#0e1621] p-3 rounded-lg border border-white/5">
        <p className="text-[10px] font-bold text-[#708499] uppercase mb-2">Specialty Markets</p>
        <div className="grid grid-cols-3 gap-2">
          {prediction.additionalMarkets.filter(m => m.name === 'Corners' || m.name === 'Cards' || m.name === 'Goals').map((market, i) => (
            <div key={i} className="bg-white/5 p-2 rounded text-center">
              <p className="text-[9px] text-[#708499] uppercase truncate">{market.name}</p>
              <p className="text-[10px] font-bold text-white truncate">{market.value}</p>
              <p className="text-[9px] text-emerald-400 font-bold">{market.probability}%</p>
            </div>
          ))}
        </div>
      </div>

      {/* Main Markets Bar */}
      <div className="grid grid-cols-2 gap-2">
        <div className="p-2.5 bg-[#0e1621] rounded border border-white/5 flex justify-between items-center">
          <div>
            <p className="text-[9px] text-[#708499] uppercase">Double Chance (1X)</p>
            <p className="text-xs font-bold text-white">{prediction.probabilities.doubleChance['1X']}%</p>
          </div>
          <div className="w-8 h-8 rounded-full border-2 border-violet-500/30 flex items-center justify-center text-[9px] font-bold text-violet-400">1X</div>
        </div>
        <div className="p-2.5 bg-[#0e1621] rounded border border-white/5 flex justify-between items-center">
          <div>
            <p className="text-[9px] text-[#708499] uppercase">BTTS Yes</p>
            <p className="text-xs font-bold text-white">{prediction.probabilities.bttsYes}%</p>
          </div>
          <div className="w-8 h-8 rounded-full border-2 border-emerald-500/30 flex items-center justify-center text-[9px] font-bold text-emerald-400">B</div>
        </div>
      </div>

      {/* Recommended Verdict */}
      <div className="bg-[#40a7e3]/10 p-3 rounded-lg border border-[#40a7e3]/20 shadow-inner relative overflow-hidden group">
        <div className="flex justify-between items-start mb-1">
          <span className="text-[10px] font-bold text-[#40a7e3] uppercase tracking-wider">Bot Verdict</span>
          <span className="text-[10px] font-bold text-white px-1.5 py-0.5 bg-[#40a7e3] rounded-sm">{prediction.confidence}% Confidence</span>
        </div>
        <p className="text-xs font-bold text-white leading-tight italic pr-8">{prediction.suggestedBet}</p>
        
        <button 
          onClick={shareToX}
          className="absolute right-2 bottom-2 w-7 h-7 bg-black rounded-full flex items-center justify-center text-white hover:bg-slate-900 transition-all border border-white/10 shadow-lg"
          title="Share to X"
        >
          <svg className="w-3.5 h-3.5" fill="currentColor" viewBox="0 0 24 24">
            <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
          </svg>
        </button>
      </div>

      {/* Sources */}
      {prediction.sources && prediction.sources.length > 0 && (
        <div className="pt-2 border-t border-white/5">
          <p className="text-[9px] text-[#708499] uppercase mb-2">Verified Sources</p>
          <div className="flex flex-wrap gap-2">
            {prediction.sources.map((source, i) => (
              <a 
                key={i} 
                href={source.uri} 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-[10px] text-[#64b5ef] hover:underline flex items-center gap-1 bg-[#17212b] px-2 py-1 rounded border border-white/5"
              >
                <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>
                {source.title.length > 15 ? source.title.substring(0, 15) + '...' : source.title}
              </a>
            ))}
          </div>
        </div>
      )}

      {/* Follow-up Suggestions */}
      {prediction.suggestedFollowUps && (
        <div className="flex flex-wrap gap-1.5 pt-1">
          {prediction.suggestedFollowUps.map((text, i) => (
            <button 
              key={i}
              onClick={() => onAction?.(text)}
              className="px-2.5 py-1 bg-[#2b5278] hover:bg-[#396996] text-white text-[10px] rounded-full transition-all shadow-sm"
            >
              {text}
            </button>
          ))}
        </div>
      )}
    </div>
  );
};

export default PredictionDisplay;
